### ISSUE TITLE
Installation issue on Google Colab

### ISSUE THREAD

**Issue by okbalefthanded** [alexandrosstergiou/adaPool#10]
Hi,
Thanks for providing a Cuda optimized implementation. While building the lib I encountered an issue with "inf" at limits.cuh. 

```
CUDA/limits.cuh(119): error: identifier "inf" is undefined

CUDA/limits.cuh(120): error: identifier "inf" is undefined

CUDA/limits.cuh(128): error: identifier "inf" is undefined

CUDA/limits.cuh(129): error: identifier "inf" is undefined

4 errors detected in the compilation of "CUDA/adapool_cuda_kernel.cu".
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1
Makefile:2: recipe for target 'install' failed
make: *** [install] Error 1
```

The following notebook provides more details with environment informations:
https://colab.research.google.com/drive/1T6Nxe2qbjKxXzo2IimFMYBn52qbthlZB?usp=sharing

**Comment by alexandrosstergiou** [comment]
Hi @okbalefthanded , can you try to change the lines to use C's [`+/- INFINITY` micro](https://en.cppreference.com/w/cpp/numeric/math/INFINITY).?

**Comment by okbalefthanded** [comment]
Hi @alexandrosstergiou , the cmath micro works fine.
the test passed. 
Thanks.
