### ISSUE TITLE
can you share the code for object detection?

### ISSUE THREAD

**Issue by OyamingO** [alexandrosstergiou/adaPool#11]

**Comment by alexandrosstergiou** [comment]
Hi @OyamingO ,

The current repository is only meant for hosting the code for adaPool. For object detection, you use:
- [this implementation](https://github.com/yhenon/pytorch-retinanet) for RetinaNet 
- [and this implementation](https://github.com/multimodallearning/pytorch-mask-rcnn) for Mask-RCNN
and adapt the corresponding models with ada(Un)Pool layers.
