### ISSUE TITLE
CAN

### ISSUE THREAD

**Issue by 1zsw123** [alexandrosstergiou/adaPool#12]

**Comment by 1zsw123** [comment]
can beta study faster？ when I use adapool2d， it is too slow that I must make the learning rate very small, I want it faster, do you have any idea? Please help,  thank you very very much.

**Comment by alexandrosstergiou** [comment]
Hi @1zsw123 ,

If you want to focus on optimizing convergence time, you can switch to a single-valued beta instead of a matrix (for each pooling window). However, throughout all experiments, I did not notice any convergence issues w.r.t. speed.

**Comment by 1zsw123** [comment]
ok， I got it.Thank you
