### ISSUE TITLE
The version of pytorch and how to deal with `nan_to_num` function in lower versions

### ISSUE THREAD

**Issue by MaxChanger** [alexandrosstergiou/adaPool#2]
Thank you for this amazing project. I saw it from SoftPool. 
After installing it, `make test`, but I got `AttributeError: module 'torch' has no attribute 'nan_to_num'`, after I checked, this function used in `idea.py` was introduced  in Pytorch 1.8.0, so the torch version in the README may need to be updated, or is there an easy way to be compatible with lower versions?

**Comment by alexandrosstergiou** [comment]
Hi @MaxChanger,

Thank you very much! Indeed the required pytorch version should be at least 1.8+ , so I've updated the `README`.
