### ISSUE TITLE
Can I use it in kaggle?

### ISSUE THREAD

**Issue by Culturenotes** [alexandrosstergiou/adaPool#7]

**Comment by alexandrosstergiou** [comment]
Hi @Culturenotes,

I have not tried installing the project on Kaggle, so I'm not sure how you will go about it.

This thread may however be helpful: https://www.kaggle.com/general/164414

**Comment by alexandrosstergiou** [comment]
I will close this for now. If you pursue this further and manage to get it to work you can share your solution.
