### ISSUE TITLE
Solution: Unresolved extern function '_Z3powdi'”

### ISSUE THREAD

**Issue by Culturenotes** [alexandrosstergiou/adaPool#8]
cuda11. 0

When I tried to build your project on win10, I encountered the following problems：
“ptxas fatal   : Unresolved extern function '_Z3powdi'”

Reason: Wrong use of pow function in Cu code
Solution: for example, pow (x, 2) can be changed to X * X

**Comment by alexandrosstergiou** [comment]
Hi @Culturenotes,

This seems to be more specific to the combination of OS+hardware+CUDA+PyTorch. 

The `pow()` function for example has been part of CUDA since double precision was introduced.

Since you were able to build the project with your change I'll close this issue.
